//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int MailId { get; set; }
        public string Remitente { get; set; }
        public string Asunto { get; set; }
        public string Contenido { get; set; }
        public string Destinatario { get; set; }
    }
}
